//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter file name for report (with .xlsx or .xls part)..
        /// </summary>
        internal static string AskForFileNames {
            get {
                return ResourceManager.GetString("AskForFileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter genre....
        /// </summary>
        internal static string AskForGenre {
            get {
                return ResourceManager.GetString("AskForGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;d like to print report on console - enter &apos;C&apos;, to save to txt file - enter &apos;T&apos;, to json - enter &apos;J&apos;....
        /// </summary>
        internal static string AskForPrintingOption {
            get {
                return ResourceManager.GetString("AskForPrintingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter report number:.
        /// </summary>
        internal static string AskForReportNumber {
            get {
                return ResourceManager.GetString("AskForReportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;d like to save to txt file - enter &apos;T&apos;, to json - enter &apos;J&apos;....
        /// </summary>
        internal static string AskForSavingFormat {
            get {
                return ResourceManager.GetString("AskForSavingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;d like to sort report - enter column name, comma and &quot;D&quot; for descending, &quot;A&quot; for ascending sorting (example &quot;Author,D&quot;.
        /// </summary>
        internal static string AskForSortingOption {
            get {
                return ResourceManager.GetString("AskForSortingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;d like to filter to get specific columns from report, enter column names separated by comma, if not - click enter.  Here is availalble columns: ID, Author, Title, Price, Genre, Available, Available Books Count, Sold Books Count..
        /// </summary>
        internal static string AskForSpecificColumns {
            get {
                return ResourceManager.GetString("AskForSpecificColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;d like to save this report to file = click &apos;s&apos; button, if not click any other key....
        /// </summary>
        internal static string AskIfSavingIsRequired {
            get {
                return ResourceManager.GetString("AskIfSavingIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For getting list of books by genre - enter 1. For getting the most profitable author - enter 2. For getting list of available authors - enter 3. For getting not filtered list of books - enter 4..
        /// </summary>
        internal static string AvailableReportsFilterInfo {
            get {
                return ResourceManager.GetString("AvailableReportsFilterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For getting report from several files - enter file names separated by comma. For getting report from all available files enter &apos;.&apos; character. Here are available files:.
        /// </summary>
        internal static string ShowMultipleFilesForReportOption {
            get {
                return ResourceManager.GetString("ShowMultipleFilesForReportOption", resourceCulture);
            }
        }
    }
}
